# Generated by Django 6.0.1 on 2026-01-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='configurable',
            field=models.JSONField(default=dict),
        ),
    ]
